name: kitchen
description: A new Flutter application.


version: 1.0.0+14

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1
  flare_splash_screen: ^4.0.0
  flutter_statusbarcolor_ns: ^0.4.0
  # flutter_statusbarcolor: ^0.2.3
  persistent_bottom_nav_bar: ^5.0.2
  flutter_custom_clippers: ^2.0.0
  intl: ^0.18.0
  percent_indicator: ^4.2.2
  shared_preferences: ^2.0.15
  logging: ^1.0.2
  dio: ^5.1.2
  google_sign_in: ^5.3.2
  rxdart: ^0.27.4
  fluttertoast: ^8.0.9
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.1.6
  json_annotation: ^4.5.0
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: any
  flutter_polyline_points: ^1.0.0
  image_picker: ^0.8.6
  fl_chart: ^0.60.0
  google_maps_flutter: ^2.2.1
  google_fonts: ^4.0.3
  buttons_tabbar: ^1.3.7+1
  permission_handler: any
#  date_time_picker: ^2.1.0
  provider: ^6.0.4
  hive: ^2.2.3
  upgrader: ^8.1.0
  # device_preview: ^1.1.0
  syncfusion_flutter_charts: ^22.2.12
  flutter_local_notifications: ^15.1.1
  auto_size_text: ^3.0.0
  flutter_hooks: ^0.18.6
  clock: ^1.1.1
  cloud_firestore: ^4.4.5
  #  flutter_local_notifications_platform_interface: ^6.0.0
  timezone: ^0.9.0
  firebase_messaging: ^14.6.7
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  #flutterfire_ui: ^0.4.3+20
  overlay_support: ^2.1.0
  #  firebase_notifications_handler: ^1.1.0
  infinite_scroll_pagination: ^3.2.0
  number_paginator: ^0.2.3
  audioplayers: ^5.1.0
  disable_battery_optimization: ^1.1.0+1
  logger: ^2.0.2
  #audioplayers: ^3.0.1

#audioplayers: ^3.0.1
  perfect_volume_control: ^1.0.5
  table_calendar: ^3.0.2
  flutter_svg: ^2.0.6
  syncfusion_flutter_datepicker: ^22.2.12
  http: ^0.13.5
  carousel_slider: ^4.2.1
  hoverover: ^0.1.1
  readmore: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/kitchen_logo.png"
  adaptive_icon_background: "assets/images/kitchen_background.png"
  adaptive_icon_foreground: "assets/images/kitchen_transparent.png"




flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/testing.mp3
    - assets/preorder.mp3
    - assets/subscription.mp3

  fonts:
    - family: productsans_bold
      fonts:
        - asset: assets/font/productsans_bold.ttf
    - family: productsans_regular
      fonts:
        - asset: assets/font/productsans_regular.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/font/CustomIcon.ttf
